version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0

  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
