version: "3.8"

services:
  database:
    image: "postgres:latest"
    container_name: "postgres"
    env_file: ./server/.env
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - ./database:/var/lib/postgresql/data

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: "server"
    env_file: ./server/.env
    ports:
      - "3001:3001"
    restart: unless-stopped
    depends_on:
      - database

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: "client"
    env_file: ./client/.env
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - database
      - server

  pgadmin:
    image: dpage/pgadmin4
    container_name: "pgadmin"
    env_file: ./server/.env
    ports:
      - "5050:80"
    restart: unless-stopped
    depends_on:
      - database
    volumes:
      - ./servers.json:/pgadmin4/servers.json
