version: "3.8"

services:
  database:
    image: "postgres:latest"
    user: postgres
    environment:
      POSTGRES_DB: "portfolio"
      POSTGRES_USER: "${POSTGRES_USERNAME}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    env_file: ./server/.env
    ports:
      - "5432:5432"
    restart: unless-stopped

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: ./server/.env
    ports:
      - "3001:3001"
    restart: unless-stopped
    depends_on:
      - database
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file: ./client/.env
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - database
      - server
    volumes:
      - ./client:/app
      - /app/node_modules

  pgadmin:
    image: dpage/pgadmin4
    env_file: ./server/.env
    ports:
      - "5050:80"
    restart: unless-stopped
