name: Client

on: [push, pull_request]

defaults:
  run:
    working-directory: ./client

jobs:
  check:
    name: Run checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
          cache-dependency-path: ./client/package-lock.json

      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: ./client/node_modules
          key: dependencies-client-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          npm ci
          npm install @microsoft/eslint-formatter-sarif

      - name: Build
        run: npm run build

      - name: Run unit tests
        run: npm test -- --coverage

      - name: Upload test coverage report
        uses: codecov/codecov-action@v3
        with:
          flags: client
          files: ./client/coverage/coverage-final.json
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Run ESLint
        run: npx eslint .
          --config .eslintrc.json
          --format @microsoft/eslint-formatter-sarif
          --output-file eslint-results.sarif
        continue-on-error: true

      - name: Upload ESLint results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ./client/eslint-results.sarif
          wait-for-processing: true
