name: ESLint

on: [push, pull_request]

jobs:
  client:
    name: Run on client
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install
          npm install @microsoft/eslint-formatter-sarif@2.1.7

      - name: Run ESLint
        run: npm run lint
        continue-on-error: true

      - name: Upload results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ./client/eslint-results.sarif
          wait-for-processing: true

  server:
    name: Run on server
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install
          npm install @microsoft/eslint-formatter-sarif@2.1.7

      - name: Run ESLint
        run: npm run lint
        continue-on-error: true

      - name: Upload results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ./server/eslint-results.sarif
          wait-for-processing: true
